# Generated by Django 2.0.6 on 2018-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
